import { describe, it, expect, beforeAll, afterAll } from "vitest";
import request from "supertest";
import { createApp } from "../src/app";
import { seedTestUsers, closeTestPool, TEST_PASSWORD } from "./setup";

const app = createApp();

async function loginAs(username: string) {
  const agent = request.agent(app);
  await agent.post("/api/v1/auth/login").send({ username, password: TEST_PASSWORD });
  return agent;
}

/**
 * Creates a patient through the real HTTP route rather than
 * setup.ts's createTestPatient() helper, which calls the Patients
 * service function directly and therefore never generates the
 * patient.create audit_logs row that route writes — the audit entry
 * only exists when the actual endpoint is exercised.
 */
async function createPatientViaApi(reception: request.Agent, fullName: string) {
  const res = await reception
    .post("/api/v1/patients")
    .send({ fullName, gender: "male", approximateAge: 30 });
  return res.body.data.patient as { id: string; fullName: string };
}

beforeAll(async () => {
  await seedTestUsers();
});

afterAll(async () => {
  await closeTestPool();
});

describe("Authorization", () => {
  it("rejects an unauthenticated request to the list endpoint", async () => {
    const res = await request(app).get("/api/v1/audit-logs");
    expect(res.status).toBe(401);
  });

  it("rejects an unauthenticated request to the detail endpoint", async () => {
    const res = await request(app).get("/api/v1/audit-logs/00000000-0000-0000-0000-000000000000");
    expect(res.status).toBe(401);
  });

  it("rejects every non-owner role from the list endpoint", async () => {
    for (const username of ["test.reception", "test.nurse", "test.doctor", "test.lab", "test.pharmacy"]) {
      const agent = await loginAs(username);
      const res = await agent.get("/api/v1/audit-logs");
      expect(res.status).toBe(403);
    }
  });

  it("rejects a non-owner role from the detail endpoint", async () => {
    const agent = await loginAs("test.reception");
    const res = await agent.get("/api/v1/audit-logs/00000000-0000-0000-0000-000000000000");
    expect(res.status).toBe(403);
  });

  it("owner can list logs", async () => {
    const owner = await loginAs("test.owner");
    const res = await owner.get("/api/v1/audit-logs");
    expect(res.status).toBe(200);
    expect(Array.isArray(res.body.data.logs)).toBe(true);
    expect(typeof res.body.data.total).toBe("number");
  });
});

describe("Real audit records from other modules are retrievable", () => {
  it("a patient.create entry generated by the Patients module can be found and read back", async () => {
    const reception = await loginAs("test.reception");
    const patient = await createPatientViaApi(reception, `Audit Log Test Patient ${Date.now()}-${Math.random()}`);
    const owner = await loginAs("test.owner");

    const res = await owner.get("/api/v1/audit-logs").query({ entity: "patients", entityId: patient.id });
    expect(res.status).toBe(200);
    expect(res.body.data.logs.length).toBeGreaterThan(0);
    const entry = res.body.data.logs.find((l: { action: string }) => l.action === "patient.create");
    expect(entry).toBeDefined();
    expect(entry.entityId).toBe(patient.id);
    expect(entry.entity).toBe("patients");
    expect(entry.user).not.toBeNull();
    expect(entry.user.username).toBe("test.reception");
  });

  it("a login.failed entry has no user object", async () => {
    const owner = await loginAs("test.owner");
    await request(app).post("/api/v1/auth/login").send({ username: "no.such.user", password: "whatever" });

    const res = await owner.get("/api/v1/audit-logs").query({ action: "login.failed", limit: 5 });
    expect(res.status).toBe(200);
    expect(res.body.data.logs.length).toBeGreaterThan(0);
    expect(res.body.data.logs[0].user).toBeNull();
  });
});

describe("Filters", () => {
  it("filters by entity", async () => {
    const reception = await loginAs("test.reception");
    const patient = await createPatientViaApi(reception, `Filter Entity Test ${Date.now()}-${Math.random()}`);
    const owner = await loginAs("test.owner");

    const res = await owner.get("/api/v1/audit-logs").query({ entity: "patients", limit: 100 });
    expect(res.status).toBe(200);
    expect(res.body.data.logs.every((l: { entity: string }) => l.entity === "patients")).toBe(true);
    expect(res.body.data.logs.some((l: { entityId: string }) => l.entityId === patient.id)).toBe(true);
  });

  it("filters by entityId", async () => {
    const reception = await loginAs("test.reception");
    const patient = await createPatientViaApi(reception, `Filter EntityId Test ${Date.now()}-${Math.random()}`);
    const owner = await loginAs("test.owner");

    const res = await owner.get("/api/v1/audit-logs").query({ entityId: patient.id });
    expect(res.status).toBe(200);
    expect(res.body.data.logs.length).toBeGreaterThan(0);
    expect(res.body.data.logs.every((l: { entityId: string }) => l.entityId === patient.id)).toBe(true);
  });

  it("filters by userId", async () => {
    const owner = await loginAs("test.owner");
    const me = await owner.get("/api/v1/auth/me");
    const ownerId = me.body.data.user.id;

    const res = await owner.get("/api/v1/audit-logs").query({ userId: ownerId, limit: 50 });
    expect(res.status).toBe(200);
    expect(res.body.data.logs.every((l: { user: { id: string } | null }) => l.user?.id === ownerId)).toBe(true);
  });

  it("filters by action", async () => {
    const reception = await loginAs("test.reception");
    await createPatientViaApi(reception, `Filter Action Test ${Date.now()}-${Math.random()}`);
    const owner = await loginAs("test.owner");

    const res = await owner.get("/api/v1/audit-logs").query({ action: "patient.create", limit: 50 });
    expect(res.status).toBe(200);
    expect(res.body.data.logs.length).toBeGreaterThan(0);
    expect(res.body.data.logs.every((l: { action: string }) => l.action === "patient.create")).toBe(true);
  });

  it("combines multiple filters together", async () => {
    const reception = await loginAs("test.reception");
    const patient = await createPatientViaApi(reception, `Combined Filter Test ${Date.now()}-${Math.random()}`);
    const owner = await loginAs("test.owner");

    const res = await owner
      .get("/api/v1/audit-logs")
      .query({ entity: "patients", entityId: patient.id, action: "patient.create" });
    expect(res.status).toBe(200);
    expect(res.body.data.logs).toHaveLength(1);
    expect(res.body.data.logs[0].entityId).toBe(patient.id);
  });

  it("date-range filtering excludes records outside the window", async () => {
    const owner = await loginAs("test.owner");
    const farFuture = new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString();

    const res = await owner.get("/api/v1/audit-logs").query({ dateFrom: farFuture });
    expect(res.status).toBe(200);
    expect(res.body.data.logs).toHaveLength(0);
    expect(res.body.data.total).toBe(0);
  });

  it("date-range filtering includes records inside the window", async () => {
    const reception = await loginAs("test.reception");
    const patient = await createPatientViaApi(reception, `Date Range Test ${Date.now()}-${Math.random()}`);
    const owner = await loginAs("test.owner");

    const dateFrom = new Date(Date.now() - 60_000).toISOString();
    const dateTo = new Date(Date.now() + 60_000).toISOString();

    const res = await owner
      .get("/api/v1/audit-logs")
      .query({ entityId: patient.id, dateFrom, dateTo });
    expect(res.status).toBe(200);
    expect(res.body.data.logs.length).toBeGreaterThan(0);
  });

  it("returns an empty result set for a filter that matches nothing", async () => {
    const owner = await loginAs("test.owner");
    const res = await owner.get("/api/v1/audit-logs").query({ entity: "no_such_entity_xyz" });
    expect(res.status).toBe(200);
    expect(res.body.data.logs).toHaveLength(0);
    expect(res.body.data.total).toBe(0);
  });
});

describe("Pagination", () => {
  it("respects the limit parameter", async () => {
    const owner = await loginAs("test.owner");
    const res = await owner.get("/api/v1/audit-logs").query({ limit: 3 });
    expect(res.status).toBe(200);
    expect(res.body.data.logs.length).toBeLessThanOrEqual(3);
    expect(res.body.data.limit).toBe(3);
  });

  it("respects the offset parameter — different pages return different records", async () => {
    const owner = await loginAs("test.owner");
    const page1 = await owner.get("/api/v1/audit-logs").query({ limit: 2, offset: 0 });
    const page2 = await owner.get("/api/v1/audit-logs").query({ limit: 2, offset: 2 });
    expect(page1.status).toBe(200);
    expect(page2.status).toBe(200);
    const ids1 = page1.body.data.logs.map((l: { id: string }) => l.id);
    const ids2 = page2.body.data.logs.map((l: { id: string }) => l.id);
    expect(ids1.some((id: string) => ids2.includes(id))).toBe(false);
  });

  it("total reflects the full filtered count, not just the current page", async () => {
    const reception = await loginAs("test.reception");
    for (let i = 0; i < 3; i++) {
      await createPatientViaApi(reception, `Pagination Total Test ${i}-${Date.now()}-${Math.random()}`);
    }
    const owner = await loginAs("test.owner");
    const res = await owner.get("/api/v1/audit-logs").query({ action: "patient.create", limit: 1 });
    expect(res.status).toBe(200);
    expect(res.body.data.logs).toHaveLength(1);
    expect(res.body.data.total).toBeGreaterThanOrEqual(3);
  });

  it("defaults to a sensible limit when none is provided", async () => {
    const owner = await loginAs("test.owner");
    const res = await owner.get("/api/v1/audit-logs");
    expect(res.status).toBe(200);
    expect(res.body.data.limit).toBe(20);
  });
});

describe("Detail endpoint", () => {
  it("retrieves a specific entry by id", async () => {
    const reception = await loginAs("test.reception");
    const patient = await createPatientViaApi(reception, `Detail Test ${Date.now()}-${Math.random()}`);
    const owner = await loginAs("test.owner");

    const listRes = await owner.get("/api/v1/audit-logs").query({ entityId: patient.id });
    const entryId = listRes.body.data.logs[0].id;

    const res = await owner.get(`/api/v1/audit-logs/${entryId}`);
    expect(res.status).toBe(200);
    expect(res.body.data.log.id).toBe(entryId);
    expect(res.body.data.log.entityId).toBe(patient.id);
  });

  it("returns 404 for a non-existent id", async () => {
    const owner = await loginAs("test.owner");
    const res = await owner.get("/api/v1/audit-logs/00000000-0000-0000-0000-000000000000");
    expect(res.status).toBe(404);
  });

  it("returns 400 for a malformed id", async () => {
    const owner = await loginAs("test.owner");
    const res = await owner.get("/api/v1/audit-logs/not-a-uuid");
    expect(res.status).toBe(400);
  });
});

describe("Malformed query parameters", () => {
  it("rejects a malformed userId (not a uuid)", async () => {
    const owner = await loginAs("test.owner");
    const res = await owner.get("/api/v1/audit-logs").query({ userId: "not-a-uuid" });
    expect(res.status).toBe(400);
  });

  it("rejects a malformed dateFrom", async () => {
    const owner = await loginAs("test.owner");
    const res = await owner.get("/api/v1/audit-logs").query({ dateFrom: "not-a-date" });
    expect(res.status).toBe(400);
  });

  it("rejects a limit above the maximum", async () => {
    const owner = await loginAs("test.owner");
    const res = await owner.get("/api/v1/audit-logs").query({ limit: 10000 });
    expect(res.status).toBe(400);
  });

  it("rejects a negative offset", async () => {
    const owner = await loginAs("test.owner");
    const res = await owner.get("/api/v1/audit-logs").query({ offset: -5 });
    expect(res.status).toBe(400);
  });

  it("rejects unknown query parameters (strict schema)", async () => {
    const owner = await loginAs("test.owner");
    const res = await owner.get("/api/v1/audit-logs").query({ notARealFilter: "x" });
    expect(res.status).toBe(400);
  });
});

describe("Viewing audit logs is not itself audited", () => {
  it("listing audit logs does not create a new audit_logs row", async () => {
    const owner = await loginAs("test.owner");
    const before = await owner.get("/api/v1/audit-logs").query({ action: "audit_log.view" });
    expect(before.body.data.total).toBe(0);

    await owner.get("/api/v1/audit-logs");
    await owner.get("/api/v1/audit-logs").query({ entity: "patients" });

    const after = await owner.get("/api/v1/audit-logs").query({ action: "audit_log.view" });
    expect(after.body.data.total).toBe(0);
  });
});
